- hosts: hpc
  become: true
  tasks:
    - name: Install Spack PKGS(1/2)
      copy:
        src: "spack_install.sh"
        dest: '/tmp/'
        owner: root
        group: root
        mode: 0777

    - name: Install Spack PKGS(2/2)
      shell: /tmp/spack_install.sh

    